### ISSUE TITLE
Questions about code for nonlinear_pt1.R and pt2

### ISSUE THREAD

**Issue by ddlee19** [macss-modeling/General-Questions#16]
Part 1:

In lines 30, 50, 53, and 83, we seem to be fitting regression splines but how come the "df" parameter is 3 + K (num of knots) rather than the 4 + K in the notes and textbook?

Part 2:

For GAMs, we always seem to be plotting f(X_1) ~ X_1 and none with the entire y ~ f_1(X_1) + f_2(X_2) model. Is this how GAMs are always used? Only analyzing each predictor one at a time rather than looking at the whole model with the response? Further, in the "Extra code for Fun" section, how is it the case that in the plots for the GAM classifier, the plots of f_1(age), f_2(fare), and f_3(gender) show y-values (of the plot, not the response of the full model) that are less than 0 or greater than 1 if Survived is a binary response?

**Comment by pdwaggoner** [comment]
Hi -  for 1: I was trying some different configurations and forgot to bump it up to 7. Good catch. But note that if you change between `df = 6` and `df = 7`, the fits are nearly identical. Thanks.

for 2: Mostly GAMs are interested in plotting each separately, as that's what we're doing (fitting unique functions to each, with different scales). But consider https://www.rdocumentation.org/packages/mgcv/versions/1.8-33/topics/plot.gam

for 3: because we aren't plotting the predicted probabilities. We are plotting marginal changes in Y, based on the `f()` of the x.
