### ISSUE TITLE
Week 5 Part 1 slides 12/28 Degree of freedom

### ISSUE THREAD

**Issue by Qiuyu-Li** [macss-modeling/General-Questions#17]
Hi Professor, hope you are having a great weekend. In the 12th page in the slides for Week 5, it says that "for a piecewise polynomial regression of dimension d, the degrees of freedom would be **d × (K + 1)**". However, based on my prior knowledge and the description in the ISL, I think the degrees of freedom should be instead ** n - d × (K + 1) **, where n is the number of observations. Would you help clarify this problem? Thank you!

**Comment by Qiuyu-Li** [comment]
A little more follow-up of the question: in ISL p278-279, it says that 

> Usually degrees of freedom refers to the number of free parameters, such as the number of coeﬃcients ﬁt in a
polynomial or cubic spline. 

However, in my memory degrees of freedom actually refers to **the number of sample moments - The number of free parameters**. Is that the definition of DF is just different in this context?

Furthermore, in ISL p278, it says

> It is possible to show that as λ increases from 0 to ∞, the eﬀective degrees of freedom, which we write dfλ, decrease from n to 2.

So under the traditional definition of DF, the effective DF should be increasing from 0 to n-2?

**Comment by Qiuyu-Li** [comment]
And another related question: how to understand "effective DF".
I found the definition of it in the slides a little bit different from that in the ISL. In ISL it says

> ghat_lambda = S_lambda * y, where ghat_lambda is the vector of fitted values (ISL p279).

Therefore, S_lambda actually measures some *deviation of ghat from y*, is that right?
But in the slides (p27) it says S_lambda is

> the smoothed ﬁtted values for each of the training observations

which, in my understanding, actually refers to the **ghat_lambda** in ISL.
So the definition of S_lambda in ISL and the slides are different?

**Comment by pdwaggoner** [comment]
Hi - 

for 1: that's not correct; the stated df is correct. I couldn't find the version you cited in ISL, and also see slide 20 here: https://www.math.ust.hk/~makchen/MSBD5013/Ch7slide.pdf

for 2: no, they are setting up discussion of "effective degrees of freedom", which follows that sentences, and is preceded by a question to set up discussion; keep reading. They are noting how to think about basic degrees of freedom in more common applications like linear regression, e.g., in which they are correct: degrees of freedom in those contexts references the number of free parameters, based on how the model is specified. And thus, the launch into discussion of effective DF and how these differ.

for 3: I don't think I understand your question. But the idea is that the "baseline" for effective DF is now essentially n-2, because of the inclusion of \lambda on the DF calculation.

for 4: Not quite. I am using "normal language" to describe the outcome, but am saying the same thing. That is "smoothed fitted values" as a I say, are different from "fitted values." That is, `S_lambda * y`, which is equivalent to `ghat_lambda`.

**Comment by Qiuyu-Li** [comment]
Thank you so much, Professor, for this very detailed and patient reply! I think I can understand the problem now.
