### ISSUE TITLE
Question about last plot from in-class coding 2/16

### ISSUE THREAD

**Issue by ddlee19** [macss-modeling/General-Questions#18]
In the last plot created in-class today, are the point plots of each group in gender and democrat signifying the mean value of each group's feelings toward Biden? I'm not sure I'm understanding what the exact metric of "Feature Impacts" is. And there is no y-value, right? The point plots are just separated vertically to create separation in the plot, correct?

Plot for reference:
![image](https://user-images.githubusercontent.com/17442853/108157900-6f0f7500-70a9-11eb-827d-36431ad3920f.png)

**Comment by pdwaggoner** [comment]
These are showing average feelings toward Biden (the Y) by gender and then by party. Also, you need to make gender and party factor (e.g., `factor(feature_name)`) to make the colors one or the other rather than an interpolated scale as it is in this figure. Notably, the coordinates are flipped, so there is a Y and an X, they are just opposite, and I removed the x axis values for easier interpretation. But technically speaking: the X axis is gender (or party): 0 or 1/ male or female, and the Y axis is feelings toward Biden, which are average group level predictions we made from the XGBoost model. I hope this helps.
