### ISSUE TITLE
question about ps2-problem2

### ISSUE THREAD

**Issue by chentian418** [macss-modeling/General-Questions#20]
Hi professor,
Can you specify a bit more on how we could fit the model using k-fold cross validation? 

My current understanding is that, given a set of hyper-parameters, for each fold we fit the data using the sub-training set(the K-1 folds) and get a measure of the model on the kth fold. Therefore, the k-fold cv is just used to conduct a more comprehensive measure of the error, and once we compare the errors across models, we'll re-train the model of the best performance using the whole train set instead of some sub-training set in the validation method.

Secondly, the k-fold cv is also used for parameter tuning, while we could also tune the parameter as the sample codes in class did, which is setting a hyper-grid and directly train the model using the entire training set without k-fold cv. And I was wondering which one should be used here. If k-fold-cv should be used for parameter tuning, will there be two cv conducted at the same time or we could combine them into one cv?

Moreover, I'm confused about how we could use k-fold cv to fit the bagging and random forest model, as they already have resampling method, i.e., bootstrapping included, are we going to conduct k-fold cv to each of the tree separately and combine the B trees together? Or how could we combine the two resampling methods in a single method?

Lastly, I want to ask for some suggestions about a uniform way to fit the model with k-fold cv, is there any codes or package we could referring to?

Thanks so much for your answering!

**Comment by chentian418** [comment]
Also, I don't find any codes about rpart and decision trees in the sample codes in class, while the problem set specify using the rpart algorithm to do decision trees. 
can we use caret instead, or would you mind providing some instructions on how to use rpart to fit the model with cv?

Thanks!

**Comment by pdwaggoner** [comment]
Thanks for the questions. They are all about CV for the most part, so I'll focus my answer there. You'd want to use cross validation in general as a best practice, whether tuning hyperparameters or not, or in my opinion, whether using bootstrapping or not. This is because CV is like an extra quality check on the generalizability of your model. If not tuning parameters, then it fits the same model to different configurations of the same set of data, and averages error. This is a great check on the overall ability of your model to learn patterns from data, and make reliable predictions. If on the other hand you are tuning hyperparameters, then CV is use for *each* version of the model. So for example, setting up a grid search across a bunch of combinations of values along many hyperparameters, you are using k-fold CV for *each* fit of the model at a given combination of hyperparameter values. Then, you are able to compare the cross-validated error across many version of a model set at many values and combinations of hyperparameters. So it's a very nested process, but it deepens the quality of your final results, and gives you more confidence about generalizing your solution to some new unseen set of data as we've said before. The same holds for bootstrapping, again in my opinion, which is based in being risk averse. I'd rather build many trees or many ensembles, and then check those out on many versions of the data to give me a good sense of the quality of the model. Again, you don't have to do this in practice, because when using bootstrap aggregation as you mentioned, you get the OOB set for free, which is a simpler way to test your model. But for the purposes of this assignment and for being as thorough as possible, I'd like k-fold CV for all models to aid in a direct model-to-model comparison. 

As far as the code, the rpart algorithm is the only one I didn't share in class, because I wanted you all to do some investigative work on your own. This is the simplest algorithm, so it shouldn't be too difficult. But yes, absolutely, use any package or any language even that you'd like to answer the problem set. I have no preference *how* you answer. I just care that you do. So for example, if you choose to use caret, consider the many model options here: <https://topepo.github.io/caret/available-models.html>

I hope this helps. Good luck!

**Comment by chentian418** [comment]
That's very clear! Thanks!
