### ISSUE TITLE
Questions on Autoencoders

### ISSUE THREAD

**Issue by egemenpamukcu** [macss-modeling/General-Questions#28]
Hi Professor, thanks for the the lecture notes, they were very illuminating this week. I had some question about AEs that I wanted to ask:

1. Can we say that the final outcome of interest for AEs is always the decoded features in the middle of the network? It seemed to me that we are using the actual output layer and the decoding process only to validate the success of the encoding process. Is the output layer used when we are working with noisy data and want to impute it to make it more complete?
2. The book chapter mentions that having  ~0 reconstruction error is useless as we are only replicating the initial input space. But if we are actually encoding the input space into smaller dimensions, and manage to decode it without almost no information loss wouldn't that be a successful application of AE?
3. Besides efficiency, is there a reason why we would go with PCA and assume linearity when we can do AE with multiple layers? Similarly, what is the downside of doing a very deep AE rather than a shallow one? I feel like, since this is unsupervised, there is no risk of overfitting, and interpretation also should not be a concern as the shallow AE is not very interpretable itself. So my initial thought is the only downside of increasing complexity by adding layers is computational efficiency. Am I missing somethig?

Thank you.

**Comment by pdwaggoner** [comment]
Thanks. Here are some responses:
1. Yeah, mostly feature extraction and reconstruction error are the things we care about. But AEs can be used for a lot of stuff, like missing data as you note, or anomaly detection, etc. 
2. It would be "successful", but at that point I'd ask why complicate this then if the space is clearly (perfectly, actually) structured? The AEs introduces unnecessary complication in interpretations, etc. So, in such a case, just use the normal input data in my opinion.
3. There isn't a major reason to go with one over the other (other than efficiency), other than depending on goals and thus your conceptualization of structure in the given data space. Namely, I like AEs way more than PCA, because we still get projection and can extract features with both, but in AEs we sort of get baked in validation, where we know we can trust the features extracted more than in PCA, because we've natively used them for a task (to reconstruct the input layer). Yeah, you could deepen the network, but then the interpretability question comes in. For AEs, this is mostly in the form of, *which hidden layer should you extract for your new features?* And if there are 10 hidden layers or something huge, we might get a great look at the reconstructed input layer, but not be able to do much with the deep features. So here again, let your goals guide you. If you care about reconstruction more than anything else, including feature extraction, then yeah go with a deep AE, and tune it until you are satisfied with the reconstructed version of the input layer. Its very much an art, in addition to being a science.
